[package]
name = "manufacturing-emu"
version = "0.0.1"
description = "Emulator for manufacturing line layouts"
repository = "https://github.com/nnaapp/Manufacturing-Line-Emulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.6.0"
log2 = "0.1.11"
opcua = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

