[package]
name = "Manufacturing Line Emulator"
description = "Emulator for manufacturing line layouts"
repository = "https://github.com/nnaapp/Manufacturing-Line-Emulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
